FORMAT: 1A
HOST: https://cqrhotel.com/

# CQR-Neuronall Integration

This is the API documentation for the Reservations microservice of CQR's platform, so in this document, you would find all the available endpoints, resources and its details.

The Reservations microservice is responsible to manage the available reservation gateways and its configurations.

# HTTP Request Basics
## Allowed HTTP methods

- `GET` - Should be used to get a list or details about a object or resource
- `POST` - Should be used to create a new object

## Typical Server Responses

- 200 `OK` - The request was successful (some API calls may return 201 instead)
- 201 `Created` `TODO` - The request was successful and the object was created
- 400 `Bad Request` `TODO` - The request could not be understood or was missing required parameters
- 404 `Not Found` `TODO` - The resource or endpoint was not found
- 500 `Internal Server Error` `TODO` - An error ocurred at try to perform the request
- 503 `Service Unavailable` `TODO` - The service is temporary unavailable, try again later



# Neuronall-CQR Test

Here we show the usage of the API as proposed by CQR first draft.

## API v1 [/api/v1/?cmd={cmd}&client_id={client_id}&apikey={apikey}]

### getTest_v1.00 [GET]
+ Parameters 
    +  cmd : `getTest_v1.00` (string) - nombre identificador de el comando
    +  client_id : `TEST` (string) - nombre identificador de el cliente
    +  apikey : `5521784ef04d6215d65b55385ec493ab` (string) - llave de autenticación de la API


+ Response 200 (application/json)

        {
            "gettest":
                {
                "client_id": "TEST",
                "error_code": "0" ,
                "error_description": "" ,
                "data": { "dateTime": "2018-07-23 12:45:05"}
                }
        }
        
        
               
### postTest_v1.00 [POST]
+ Attributes 
    +  cmd : `getTest_v1.00` (string) - nombre identificador de el comando
    +  client_id : `TEST` (string) - nombre identificador de el cliente
    +  apikey : `5521784ef04d6215d65b55385ec493ab` (string) - llave de autenticación de la API

+ Request (application/json)

        %7B%22cmd%22%3A%22getTest_v1.00%22%2C%22client_id%22%3A%22TEST%22%2C%22apikey%22%3A%225521784ef04d6215d65b55385ec493ab%22%7D

+ Response 200 (application/json)

        {
            "gettest":
                {
                "client_id": "TEST",
                "error_code": "0" ,
                "error_description": "" ,
                "data": { "dateTime": "2018-07-23 12:45:05"}
                }
        }
        


## API v2 [/api/v2/?hotel={hotel}&desde={desde}&hasta={hasta}&apikey={apikey}&nombre={nombre}&apellido={apellido}&email={email}&children={children}&grownups={grownups}]

Here we show the usage of the API as proposed by Neuronall, as a second draft.

### getTest_v2.00 [GET]
+ Parameters 
    +  hotel : `InterplazaHotel` (string) - nombre identificador de el hotel
    +  desde : `2018-07-23` (string) - fecha de inicio de reserva
    +  hasta : `2018-07-30` (string) - fecha de fin de reserva
    +  apikey : `5521784ef04d6215d65b55385ec493ab` (string) - llave de autenticación de la API
    +  nombre : `Margaret` (string) - nombre de la persona
    +  apellido : `Tatcher` (string) - apellido de la persona
    +  email : `theIronLady@gmail.com` (string) - email de la persona
    +  children : `0` (integer) - cantidad de niños
    +  grownups : `0` (integer) - cantidad de adultos


+ Response 200 (application/json)

        [
                {
                "nombre_habitación": "11",
                "image": "http://yoguitec.com/cqr/wp-content/uploads/2018/07/Habitaciones-Doble-Matrimonial-Standard-925x465.jpg" ,
                "data": { "etc": "datos varios"}
                },
                {
                "nombre_habitación": "11",
                "image": "http://yoguitec.com/cqr/wp-content/uploads/2018/07/Habitaciones-Doble-Matrimonial-Standard-925x465.jpg" ,
                "data": { "etc": "datos varios"}
                }
        ]